openapi: 3.0.3
info:
  title: kafka connect API
  description: |-
    defined using Open API and swagger-editor tool
  version: 0.0.1
externalDocs:
  description: find out more about swagger.io
  url: http://swagger.io
servers:
  - name: connect-api
    url: http://localhost:8083
    description: kafka connect service
paths:
  /connector-plugins:
    description: |
      get registered connectors
    get:
      summary: get a list of connectors
      tags:
        - connectors
      operationId: getConnectors
      responses:
        '200':
          description: success
          content:
            application/json:
  /connectors:
    description: |
      configure connectors
    post:
      summary: provide connector for db via config object 
      tags:
        - connectors
      operationId: postConnector
      requestBody:
        description: Create/register new connector
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/connector
      responses:
        '200':
          description: success
          content:
            application/json:

# POST  http://localhost:8083/connectors --> To register the kafka connector
# {
#   "name": "inventory-connector",
#   "config": {
#     "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
#     "database.hostname": "postgres",
#     "database.port": "5432",
#     "database.user": "postgres",
#     "database.password": "postgres",
#     "database.dbname" : "postgres",
#     "database.server.name": "dbserver1",
#     "table.include.list": "inventory.customers"
#
#   }
# }   


components:
  schemas:
    connector:
      required:
        - name
        - config
      type: object
      properties:
        name:
          type: string
          example: "inventory-connector"
        config:
          type: object
          $ref: '#/components/schemas/config'
    config:
      type: object
      properties:
        connector.class:
          type: string
          example: "io.debezium.connector.postgresql.PostgresConnector"
        database.hostname:
          type: string
          example: "postgres"
        database.port:
          type: string
          example: "5432"
        database.user:
          type: string
          example: "postgres"
        database.password:
          type: string
          example: "postgres"
        database.dbname:
          type: string
          example: "postgres"
        database.server.name:
          type: string
          example: "dbserver1"
        table.include.list:
          type: string
          example: "inventory.customers" 

# POST  http://localhost:8083/connectors --> To register the kafka connector
  

