openapi: 3.0.3
info:
  title: E-store API
  description: |-
    defined using Open API and swagger-editor tool
  version: 0.0.1
externalDocs:
  description: find out more about swagger.io
  url: http://swagger.io
servers:
  - name: kafka cluster
    url: http://localhost:8001
paths:
  /consumer:
    description: |
      check health of consumer
    get:
      tags:
        - consumer
      operationId: checkHealthConsumers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health-status'
  /consumer/orders:
    get:
      tags:
        - orders
      summary: get unprocessed orders
      operationId: getOrders
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orders'
        '405':
          description: Invalid input

  /producer:
    description: |
      check health of producer
    get:
      tags:
        - producer
      operationId: checkHealthProducers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health-status'
  /producer/orders:              
    post:
      tags:
        - orders
      summary: produce new order
      operationId: producerOrder
      requestBody:
        description: produce new order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'          
        '405':
          description: Invalid input

components:
  schemas:
    health-status:
      required:
        - message
      type: object
      properties:
        message:
          type: string
    client:
      required:
        - id
        - firstName
        - lastName
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstName:
          type: string
          example: joe
        lastName:
          type: string
          example: Schmoe  
    clients:
      type: array
      items:
        $ref: '#/components/schemas/client'
    product:
      required:
        - id
        - description
        - title
        - price
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: "toshiba XYZ"  
        description:
          type: string
          example: "laptop computer"
        price:
          type: float
          example: 100.5  
    products:
      type: array
      items:
        $ref: '#/components/schemas/product'    
    order:
      required:
        - id
        - clientId
        - productId
        - quantity
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        clientId:
          type: integer
          format: int64
          example: 10
        productId:
          type: integer
          format: int64
          example: 10
        quantity:
          type: integer
          format: int64
          example: 10
    orders:
      type: array
      items:
        $ref: '#/components/schemas/order'

    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: "internal error"
  

