version: '3.5'

networks:
  kafka-net:
    driver: bridge

volumes:
  clients_db_vol:

include: 
  - ./compose-files/kafka-cluster.yaml
  - ./compose-files/kafka-connect.yaml
  - ./compose-files/microservices.yaml

services:
  
  adminer:
    image: adminer
    container_name: adminer
    networks: 
      - kafka-net  
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: clients-db:5432

  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger-ui-container
   ports:
    - "80:8080"
   networks: 
    - kafka-net
   volumes:
    - ${PWD}://usr/share/nginx/html/api
   environment:
     URLS: "[{ url: \"api/design/api-def.yaml\", name: \"e-store API definitions\" },
             { url: \"api/kafka-connect/connect-api-def.yaml\", name: \"debezium-connect API definitions\" },
             { url: \"api/kafka-connect/schema-registry-api-def.yaml\", name: \"schema registry API definition\" }]" 