version: '3.5'

networks:
  kafka-net:
    driver: bridge

volumes:
  clients_db_vol:


services:
  
  client-api:
    build: 
      context: ../services/clients
      dockerfile: Dockerfile
    container_name: clients-api
    hostname: cleints-api
    networks:
      - kafka-net
    ports:
      - "4000:4000"
    environment:
      - HOST=clients-db
    depends_on:
      - clients-database  

  clients-database:
    build: 
      context: ../services/clients/database
      dockerfile: Dockerfile
    restart: always
    container_name: clients-db
    hostname: clients-db
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=my-strongest-password
      - POSTGRES_DB=clients-db
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - clients_db_vol:/var/lib/postgresql/data/
    networks:
      - kafka-net
   


