version: '3.5'

networks:
  kafka-net:
    driver: bridge

volumes:
  clients_db_vol:
  products_db_vol:
  sink_db_vol:

services:
  
  client-api:
    build: 
      context: ../services/clients
      dockerfile: Dockerfile
    container_name: clients-api
    hostname: cleints-api
    networks:
      - kafka-net
    ports:
      - "4000:4000"
    environment:
      - HOST=clients-db
    depends_on:
      - clients-database  

  clients-database:
    build: 
      context: ../services/clients/database
      dockerfile: Dockerfile
    restart: always
    container_name: clients-db
    hostname: clients-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-strongest-password
      - POSTGRES_DB=clients-db
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - clients_db_vol:/var/lib/postgresql/data/
    networks:
      - kafka-net
   
  products-api:
    build: 
      context: ../services/products
      dockerfile: Dockerfile
    container_name: products-api
    hostname: orders-api
    networks:
      - kafka-net
    ports:
      - "4001:4001"
    environment:
      - HOST=products-db
      - PORT=4001
    depends_on:
      - products-database  

  products-database:
    build: 
      context: ../services/products/database
      dockerfile: Dockerfile
    restart: always
    container_name: products-db
    hostname: products-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-strongest-password
      - POSTGRES_DB=products-db
      - PGDATA=/var/lib/postgresql/data/
    ports:
      #N.B. The port 5433 is mapped to 5432 to avoid conflicts with the clients-database
      # the URL via adminer tool will be still on port 5432: i.e. products_db:5432  
      - 5433:5432
    volumes:
      - products_db_vol:/var/lib/postgresql/data/
    networks:
      - kafka-net

  sink-database:
    build: 
      context: ./db-setup/postgresql/
      dockerfile: Dockerfile
    restart: always
    container_name: sink-db
    hostname: sink-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-strongest-password
      - POSTGRES_DB=sink-db
      - PGDATA=/var/lib/postgresql/data/
    ports:
      #N.B. The port 5433 is mapped to 5432 to avoid conflicts with the clients-database
      # the URL via adminer tool will be still on port 5432: i.e. sink_db:5432  
      - 5434:5432
    volumes:
      - sink_db_vol:/var/lib/postgresql/data/
    networks:
      - kafka-net